[package]
name="main"
version="0.1.0"
edition="2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow="1.0"

[profile.release]
debug=true
lto=true
codegen-units=1
panic='abort'
opt-level=3
