[package]
name = "sudoku-solver"
version = "3.0.0"
edition = "2024"

[dependencies]
# tikv-jemallocator = "0.5"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
target-cpu = "native"
panic = "abort"
